name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests and generate JSON report
      run: npx cucumber-js --format json:reports/cucumber_report.json
    - name: Generate HTML report
      if: always()
      run: node htmlReportGenerator.js
    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report
        path: reports/
        retention-days: 30